title: Daniel (Ding Guo) Li # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
AI and data-focused eCommerce leader with 6+ years’ experience driving digital growth through analytics, experimentation, and customer-centric optimisation. Strong commercial background combined with hands-on data science and AI training, including Python, SQL, statistical analysis, predictive modelling, and machine learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/danliwork//">LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3KN5FS6B4P # your Google Analytics tracking ID here
