title: Daniel (Ding Guo) Li # your name (or website title) here
tagline: Data Science | AI | Data Analysis
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/Daniel Li - CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/danliwork/">LinkedIn</a> |
  <a href="https://github.com/ctrl-alt-dan">GitHub</a>
  </p>
  <h3>About</h3>
  <p align="justify">
  Data-focused analytics professional with 6+ years of experience using data to drive digital performance, customer insights, and business decision-making. 
  <br><br>
  Recently completed a Certificate in Data Science & AI with hands-on experience in Python, SQL, statistical analysis, machine learning, and predictive modelling. Experienced in data cleaning, exploratory analysis, experimentation, and translating complex datasets into clear insights that improve revenue, operational efficiency, and customer experience.
  <br><br>
  </p>
  <!-- Contact / Social Block -->
  <h3>Contact</h3>
  <div class="profile-links">
    <div class="profile-item">
      <img src="/assets/nearby.png" alt="Location" class="profile-icon">
      <span>Sydney, Australia</span>
    </div>
  
    <div class="profile-item">
      <img src="/assets/phone.png" alt="Phone" class="profile-icon">
      <a href="tel:+61450051428">0450 051 428</a>
    </div>
  
    <div class="profile-item">
      <img src="/assets/email.png" alt="Email" class="profile-icon">
      <a href="mailto:daniel@lifamily.me">daniel@lifamily.me</a>
    </div>
  </div>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

