title: Daniel (Ding Guo) Li # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-focused analytics professional with 6+ years of experience using data to drive digital performance, customer insights, and business decision-making. 
  <br><br>
  Recently completed a Certificate in Data Science & AI with hands-on experience in Python, SQL, statistical analysis, machine learning, and predictive modelling. Experienced in data cleaning, exploratory analysis, experimentation, and translating complex datasets into clear insights that improve revenue, operational efficiency, and customer experience. 
  <br><br>
  <a href="https://www.linkedin.com/in/danliwork//">LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3KN5FS6B4P # your Google Analytics tracking ID here
